# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/etc" =
    {
      device = "/dev/disk/by-uuid/05f54314-1c18-4da8-9415-1adc8783717a";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  boot.initrd.luks.devices."crypt".device = "/dev/disk/by-uuid/3fe96268-2ce4-42f5-9dd3-72be55b3def1";

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/05f54314-1c18-4da8-9415-1adc8783717a";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/05f54314-1c18-4da8-9415-1adc8783717a";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/05f54314-1c18-4da8-9415-1adc8783717a";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/14F5-1596";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
